version: '3.8'

services:
  epg-merger:
    build: .
    container_name: epg-merger
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=UTC

