version: '3.8'

services:
  epg-merger:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: epg-merger-prod
    ports:
      - "5000:5000"
    volumes:
      - epg_data:/app/data
    restart: unless-stopped
    environment:
      - TZ=UTC
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  epg_data:
    driver: local
